version: "3.7"
services:
  app:
    build:
      args:
        user: mormbathie
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: unipro-exam
    container_name: unipro-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - unipro

  db:
    image: mysql:5.7
    container_name: unipro-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3307"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - unipro

  nginx:
    image: nginx:alpine
    container_name: unipro-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - unipro

networks:
  unipro:
    driver: bridge
